---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfe-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cfe-nginx-deployment
  template:
    metadata:
      labels:
        app: cfe-nginx-deployment
    spec:
      containers:
        - name: cfe-nginx-container
          image: codingforentrepreneurs/cfe-nginx:latest
          imagePullPolicy: Always
          ports:
            - name: cfe-nginx-port
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cfe-nginx-service
spec:
  selector:
    app: cfe-nginx-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http-port
      targetPort: cfe-nginx-port



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cfe-nginx-certificate
  namespace: default
spec:
  secretName: cfe-nginx-tls-secret
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cfe-nginx.terraformingkubernetes.com
  dnsNames:
  - cfe-nginx.terraformingkubernetes.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cfe-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
   - host: cfe-nginx.terraformingkubernetes.com
     http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cfe-nginx-service
              port:
                name: http-port
  tls:
    - hosts:
      - cfe-nginx.terraformingkubernetes.com
      secretName: cfe-nginx-tls-secret